name: Release

on:
    release:
        types:
            - published
            - edited

jobs:
    create-release:
        name: Build and Attach to Release
        runs-on: ubuntu-latest
        steps:
            - name: Install archive tools
              run: sudo apt install zip

            - name: Checkout source code
              uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.repository.default_branch }}

            - name: Setup bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Install dependencies
              run: cd web && bun install

            - name: Run build
              run: bun run build
              working-directory: web
              env:
                  CI: false

            - name: Bundle files
              run: |
                  ls
                  mkdir -p ./temp/minimal-hud
                  mkdir -p ./temp/minimal-hud/web/
                  cp ./{LICENSE,README.md,fxmanifest.lua,require.lua} ./temp/minimal-hud
                  cp -r ./{config,modules,stream} ./temp/minimal-hud
                  cp -r ./dist ./temp/minimal-hud/
                  cd ./temp && zip -r ../minimal-hud.zip ./minimal-hud

            - name: Upload to Existing Release
              uses: actions/upload-release-asset@v1
              id: auto_release
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ./minimal-hud.zip
                  asset_name: minimal-hud.zip
                  asset_content_type: application/zip

